[project]
name = "multi_agent_research_assisstant"
version = "0.1.0"
description = "Multi_Agent_Research_Assisstant using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=1.15.15"
]

[project.scripts]
multi_agent_research_assisstant = "multi_agent_research_assisstant.main:run"
run_crew = "multi_agent_research_assisstant.main:run"
train = "multi_agent_research_assisstant.main:train"
replay = "multi_agent_research_assisstant.main:replay"
test = "multi_agent_research_assisstant.main:test"
run_with_trigger = "multi_agent_research_assisstant.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
project_id = "24f0d529-77e3-4777-a0e3-6a50a8851652"
